# Generated by Django 5.2.16 on 2026-07-20 16:33

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
        ("messaging", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("unscored", "Unscored"),
                    ("positive", "Positive"),
                    ("neutral", "Neutral"),
                    ("negative", "Negative"),
                ],
                default="unscored",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sentiment_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="sentiment_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("portal", "Portal"),
                            ("email", "Email"),
                            ("sms", "Sms"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=120)),
                ("detail", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.firm",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects_unscoped",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cadence_days", models.PositiveIntegerField(default=14)),
                (
                    "next_run_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in",
                        to="cases.portalcase",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.firm",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects_unscoped",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_unscoped", django.db.models.manager.Manager()),
            ],
        ),
    ]
