# Generated by Django 5.2.16 on 2026-07-17 17:11

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uploader_type",
                    models.CharField(
                        choices=[("client", "Client"), ("staff", "Staff")],
                        max_length=10,
                    ),
                ),
                ("uploader_name", models.CharField(blank=True, max_length=200)),
                ("filename", models.CharField(max_length=300)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("s3_key", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("uploaded", "Uploaded"),
                            ("scanning", "Scanning"),
                            ("available", "Available"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="cases.portalcase",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.firm",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CustodyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("scanned", "Scanned"),
                            ("viewed", "Viewed"),
                            ("downloaded", "Downloaded"),
                            ("exported", "Exported"),
                        ],
                        max_length=15,
                    ),
                ),
                ("actor", models.CharField(max_length=200)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.firm",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custody",
                        to="evidence.evidencefile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_unscoped", django.db.models.manager.Manager()),
            ],
        ),
    ]
