# Generated by Django 5.2.16 on 2026-07-17 17:11

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "case_type",
                    models.CharField(default="Motor Vehicle Accident", max_length=80),
                ),
                ("external_source", models.CharField(blank=True, max_length=40)),
                ("external_id", models.CharField(blank=True, max_length=80)),
                (
                    "canonical_stage",
                    models.CharField(
                        choices=[
                            ("intake", "Getting Started"),
                            ("treatment", "Medical Treatment"),
                            ("records", "Gathering Records"),
                            ("demand", "Demand Preparation"),
                            ("negotiation", "Negotiation"),
                            ("litigation", "Litigation"),
                            ("settlement", "Settlement"),
                            ("closed", "Case Closed"),
                        ],
                        default="intake",
                        max_length=20,
                    ),
                ),
                ("stage_label_raw", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("date_of_incident", models.DateField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_firm_touch_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("next_step_note", models.CharField(blank=True, max_length=300)),
                (
                    "attorney",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attorney_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="clients.portalclientuser",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.firm",
                    ),
                ),
                (
                    "point_of_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="poc_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CaseStageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_stage", models.CharField(blank=True, max_length=20)),
                (
                    "to_stage",
                    models.CharField(
                        choices=[
                            ("intake", "Getting Started"),
                            ("treatment", "Medical Treatment"),
                            ("records", "Gathering Records"),
                            ("demand", "Demand Preparation"),
                            ("negotiation", "Negotiation"),
                            ("litigation", "Litigation"),
                            ("settlement", "Settlement"),
                            ("closed", "Case Closed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.firm",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_events",
                        to="cases.portalcase",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="portalcase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("firm", "external_source", "external_id"),
                name="uniq_case_external_ref_per_firm",
            ),
        ),
    ]
