# Generated by Django 5.2.16 on 2026-07-20 16:33

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("clients", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GrowthSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("referral", "Referral"),
                            ("review", "Review"),
                            ("household", "Household"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("sent", "Sent"),
                            ("converted", "Converted"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="suggested",
                        max_length=12,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actioned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growth_signals",
                        to="cases.portalcase",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.firm",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="NpsSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("stage_move", "Stage Move"),
                            ("settlement", "Settlement"),
                            ("periodic", "Periodic"),
                        ],
                        default="stage_move",
                        max_length=15,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="cases.portalcase",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="clients.portalclientuser",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.firm",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="UpdateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("delay", "Delay"),
                            ("setback", "Setback"),
                            ("milestone", "Milestone"),
                            ("request", "Request"),
                        ],
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body", models.TextField()),
                ("is_default", models.BooleanField(default=True)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.firm",
                    ),
                ),
            ],
            options={
                "ordering": ["kind"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_unscoped", django.db.models.manager.Manager()),
            ],
        ),
    ]
