# Generated by Django 5.2.16 on 2026-07-20 16:33

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
        ("docintel", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="docrecord",
            name="ai_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="docrecord",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CaseNarrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("ai_generated", models.BooleanField(default=False)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narrative",
                        to="cases.portalcase",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.firm",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects_unscoped",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_unscoped", django.db.models.manager.Manager()),
            ],
        ),
    ]
