# Generated by Django 5.2.16 on 2026-07-20 16:33

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectorConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="pm", max_length=40)),
                ("enabled", models.BooleanField(default=False)),
                ("shared_secret", models.CharField(blank=True, max_length=128)),
                ("stage_map", models.JSONField(blank=True, default=dict)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("last_reconcile_at", models.DateTimeField(blank=True, null=True)),
                (
                    "firm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connector",
                        to="tenants.firm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InboundEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("case.upserted", "Case upserted"),
                            ("client.upserted", "Client upserted"),
                            ("document.added", "Document added"),
                            ("contact.logged", "Contact logged"),
                            ("appointment.upcoming", "Appointment upcoming"),
                            ("case.closed", "Case closed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source", models.CharField(default="pm", max_length=40)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("applied", "Applied"),
                            ("failed", "Failed"),
                            ("dead", "Dead"),
                        ],
                        default="received",
                        max_length=10,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=500)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.firm",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("firm", "idempotency_key"),
                        name="uniq_inbound_idempotency_per_firm",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_unscoped", django.db.models.manager.Manager()),
            ],
        ),
    ]
